# You need to provide details about yourself that we can use to contact you.
[user]
username = "DaInfLoop"
email = "backupharoongames100@gmail.com"

[records]
CNAME = "591d5c54-24e1-4006-801a-326638cfbcd7.id.repl.co"
TXT = "replit-verify=591d5c54-24e1-4006-801a-326638cfbcd7"
