[user]
username = "laughingsheep"
email = "host.umaybegay@thejodo.com"
discord = "Jodo#3210"

[records]
CNAME = "50771d4f-c677-4797-9015-8184e3ca89e5.id.repl.co"
TXT = "replit-verify=50771d4f-c677-4797-9015-8184e3ca89e5"
