name: Auto Assign & Labeller
on:
  pull_request:
    types:
      - opened
    paths:
      - 'domains/**'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CONFIG_FILE: '.github/auto-assign-config.yml'
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
